/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import javax.swing.JFrame;

/**
 *
 * @author Dell
 */
public class MYABOUT extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MYABOUT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1, 1));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1000, 600));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1010, 2300));

        jPanel3.setMinimumSize(new java.awt.Dimension(1010, 2300));
        jPanel3.setPreferredSize(new java.awt.Dimension(978, 2300));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("FrankRuehl", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(231, 231, 202));
        jLabel8.setText("ABOUT OUR GYM");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(241, 218, 167));
        jLabel10.setText("1.PERSONAL TRAINING");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ptrainer.jpg"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel6.setBackground(new java.awt.Color(246, 210, 174));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(241, 218, 167));
        jLabel6.setText("2.DEDICATED FUNCTIONAL TRAINING SPACE");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GYM.jpg"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(241, 218, 167));
        jLabel13.setText("3.GROUP FITNESS CLASSES");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 830, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CLASSES.jpg"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 900, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(241, 218, 167));
        jLabel12.setText("4.MODERN EQUIPNMENTS");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1210, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EQP.jpg"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1280, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(241, 218, 167));
        jLabel11.setText("5.NUTRITIONAL PROGRAMS AND MEAL PLAN");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1590, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diet.jpg"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1660, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(241, 218, 167));
        jLabel9.setText("6.COMMUNITY  EVENTS AND CHALLENGES");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1930, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FUN.jpg"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 2000, -1, -1));

        jLabel15.setBackground(new java.awt.Color(165, 133, 113));
        jLabel15.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro Medium", 0, 14)); // NOI18N
        jLabel15.setText("<html>Group classes are a fun and motivating way for members to\nexercise in a social environment. Offering a variety of classes\nappeals to a broader audience and encourages members to try\ndifferent workouts.<br>\nClass Variety: Yoga, spinning, Zumba, pilates, strength training, and\nboot camps for all fitness levels.<br>\nExpert Instructors: Certified instructors ensure members are\nperforming exercises correctly and safely while providing motivation.<br>\nClass Scheduling Flexibility: Offering classes at different times\nduring the day to cater to different schedules, including early\nmorning, lunchtime, and evening.</html?\n");
        jLabel15.setToolTipText("");
        jLabel15.setOpaque(true);
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 887, 450, 234));

        jLabel16.setBackground(new java.awt.Color(165, 133, 113));
        jLabel16.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro Medium", 0, 14)); // NOI18N
        jLabel16.setText("<html>Your fitness journey is unique. That’s why at Sunshine  Gym, our<br>\ncertified trainers craft a personal training program tailored just for you.<br>\nAccelerate your fitness and weight loss goals with our expert blend of\ncardio, strength training, and the latest in fitness technology.<br>\nKEY FEATURES OF PERSONAL TRAINNER:<br>\n1.One-on-One Coaching<br>\n2.Progress Tracking<br>\n3.Motivation and Accountability<br>\n4.Specialized Programs</html>\n");
        jLabel16.setToolTipText("");
        jLabel16.setOpaque(true);
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 430, 200));

        jLabel17.setBackground(new java.awt.Color(165, 133, 113));
        jLabel17.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro Medium", 0, 14)); // NOI18N
        jLabel17.setText("<html>Functional training focuses on improving everyday movement\nand strength through exercises that mimic real-life activities.<br>\nA gym with a dedicated area for functional training attracts members\nlooking for a versatile and dynamic workout.<br>\nEquipment: The area includes battle ropes, kettlebells, \nresistance bands, suspension trainers (e.g., TRX), medicine balls\nand plyometric boxes.<br>\nVersatility: This space can be used for bodyweight exercises,\nhigh-intensity training, offering a range of training options.</html>");
        jLabel17.setToolTipText("");
        jLabel17.setOpaque(true);
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 450, 170));

        jLabel18.setBackground(new java.awt.Color(165, 133, 113));
        jLabel18.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro Medium", 0, 14)); // NOI18N
        jLabel18.setText("<html>Organizing community events fosters camaraderie and keeps\nmembers engaged.<br>\nFitness Challenges: Monthly or seasonal challenges (e.g., weight loss\ncompetitions, step challenges) to motivate members and create a\nsense of community.<br>\nWorkshops and Seminars: Guest speakers or experts on health and\nwellness topics to educate members and provide additional value.<br>\nSocial Events: Group outings, charity events, or fitness expos that\nallow members to connect outside of workouts.</html>");
        jLabel18.setToolTipText("");
        jLabel18.setOpaque(true);
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 2000, 450, 170));

        jLabel19.setBackground(new java.awt.Color(165, 133, 113));
        jLabel19.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro Medium", 0, 14)); // NOI18N
        jLabel19.setText("<html>Modern, well-maintained equipment is essential for attracting and retaining gym members. The gym should offer a variety of machines, free weights, and functional training tools to cater to all fitness levels and workout preferences.<br> Cardio Equipment: Treadmills, ellipticals, rowing machines, and bikes with built-in entertainment systems or interactive workout programs.<br>  Strength Training Machines: A wide range of resistance machines and free weights (dumbbells, barbells) for all muscle groups.<br>  Functional Fitness Area: Space for bodyweight exercises, resistance bands, kettlebells, and medicine balls for dynamic workouts.</html> ");
        jLabel19.setToolTipText("");
        jLabel19.setOpaque(true);
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 1270, 450, 234));

        jLabel20.setBackground(new java.awt.Color(165, 133, 113));
        jLabel20.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro Medium", 0, 14)); // NOI18N
        jLabel20.setText("<html>Supporting members with nutritional guidance helps them\nachieve their fitness goals more effectively.\n\nNutrition Workshops: Regular workshops led by nutritionists on topics\nlike meal prep, healthy eating, and dietary strategies.<br>\nPersonalized Meal Plans: Customized meal plans based on individual\nfitness goals, dietary restrictions, and preferences.<br>\nHealthy Snack Bar: On-site healthy snack options and supplements\nfor post-workout nutrition.</html>");
        jLabel20.setToolTipText("");
        jLabel20.setOpaque(true);
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 1660, 450, 150));

        jButton1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton1.setText("x");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 45, -1, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about page.png"))); // NOI18N
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane1.setViewportView(jPanel3);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        MYHOMEPAGE hp = new MYHOMEPAGE();
        hp.setVisible(true);
        hp.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MYABOUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MYABOUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MYABOUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MYABOUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MYABOUT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
